from .announcements import _AnnouncementPageHandler
from .attendance import _AttendancePageHandler
from .course_detail import _CourseDetailPageHandler
from .courses import _CoursesPageHandler
from .esa_result import _ResultsPageHandler
from .material_links import _MaterialLinksHandler
from .profile import _ProfilePageHandler
from .seating_information import _SeatingInformationHandler
from .semester import _SemesterHandler
from .unit import _UnitPageHandler
