from .semester import SemesterHandler
from .seating_information import SeatingInformationHandler
from .courses import CoursesPageHandler
from .course_detail import CourseDetailPageHandler
from .unit import UnitPageHandler 
from .material_links import MaterialLinksHandler
from .attendance import AttendancePageHandler
from .profile import ProfilePageHandler
from .announcements import AnnouncementPageHandler
from .esaresult import ResultsPageHandler